---
title: "A Partial Comparison Between 52-Week High Method and Industry Momentum Method"
output: html_document
---

main("Abstract")
We replicate the comparison between the 52-week high strategy and the industry momentum strategies in George and Hwang (2004). We replicate their analysis with David Kane's large cap stock data from 1998 to 2007, and compare our results to the results in the original paper. ...

Introduction

In this paper, we replicate part of the comparison between the industry momentum strategies and the 52-week high strategy in George and Hwang (2004). The first industry momentum strategy is developed by Jagadeesh and Titman (1993). The JT strategy believes an increase in past stock return tends to maintain in the long run, so increasing past return signifies further increment in future. The second industry momentum strategy is developed by Moskowitz and Grinblatt (1999). The MG strategy believes the momentum exists not in individual stock return but in industry as a whole. If the return of a whole industry is high in the past, such return will be high in the future as well. The 52-week high strategy is developed by George and Hwang (2004). This strategy believes that if a stock price approaches its highest price in the past 52 weeks, the return of the stock tends to be high, and vice versa.

The data we use here is the large cap US stocks from 1998 to 2007, given by Professor David Kane in Williams College. We apply each of the JT and MG strategies with two kinds of data. We first calculate the past stock return in JT strategy and past industry return in MG strategy with 6-month-long data, and then we extend the data to 12 months.
The data for 52-week high strategy is fixed at 52 the past 52 weeks, so in other words the data is always about the stock prices in the last year.

JT strategy calculates the cumulative return of individual stock. At the end of every month, the strategy calculates the cumulative return of every stock in the past several months and ranks stocks according to their cumulative return. The top 30% of the stock with high cumulative return in the past are expected to perform well and classified as "winners." The opposite 30% of the stocks are "losers." The strategy is to buy winners and short losers for 6 months. The same method is employed for the MG strategy, except that MG strategy aims at cumulative industry return instead of individual stock return. The 52-week high strategy uses the data of the past 52 weeks, which we simplified as a whole year, and compare the current price of the stock to its highest price in the past year. The stocks are ranked according to the ratio \frac{current.price}{highest.price}. The strategy is to buy the top 30% stocks with the highest ratios and the bottom 30% with the lowest ratios. The stocks will also be held for 6 months. At the end of each month, for each strategy we create a separate protfolio that selects the stocks based on the data of past 6 or 12 months, and each protfolio is going to be held for 6 months. When we calculate the return of a strategy in a single month, there will be 6 protfolios operating at the same time, since we create a new protfolio every month and each of the protfolios works for 6 months. We finally calculate the average return of each of the three strategies from 1999 to 2007 and compare the return of those strategies to see which one can earn a higher return.